# Generated by Django 3.1.1 on 2020-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
